name: Trigger for SQS
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
env:
  REPO: $GITHUB_REPOSITORY
jobs:
  send-build-request:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: echo $GITHUB_REPOSITORY
      - name: Verify with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-skip-session-tagging: true
      - name: Send Message to SQS
        uses: isbang/sqs-action@v0.1.1
        with:
          sqs-url: https://sqs.us-east-1.amazonaws.com/404820766655/trigger-build
          message: ${{ env.REPO }}
